"""Shared logical geometry for CaveViewer's retained Tk application shell."""

from __future__ import annotations


TK_GRID_UNIT = 4

SHELL_REFERENCE_WIDTH = 1080
SHELL_SIDEBAR_WIDTH = 220
SHELL_SIDEBAR_GUTTER = 16
SHELL_MAIN_GUTTER = 32
SHELL_SCROLLBAR_RAIL_WIDTH = 16
SHELL_CONTENT_WIDTH_AT_REFERENCE = (
    SHELL_REFERENCE_WIDTH - SHELL_SIDEBAR_WIDTH - (2 * SHELL_MAIN_GUTTER)
)

SHELL_TOP_INSET = 16
PRIMARY_ROW_HEIGHT = 44
TABBED_CONTENT_GAP = 24

CARD_PADDING = 24
CARD_GAP = 24
CARD_RADIUS = 10

COMPACT_CONTROL_HEIGHT = 36
REGULAR_CONTROL_HEIGHT = 40
PROMINENT_CONTROL_HEIGHT = 44
PROMINENT_ACTION_WIDTH = 160
ACTION_GAP = 16
FOOTER_GAP = 32

NAV_ICON_SIZE = 18
COMPACT_NUMERIC_WIDTH = 90
